version: "3"
services:
  backend:
    build: ./backend
    command: yarn start
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000

  # frontend:
  #   build: ./frontend
  #   command: yarn serve
  #   volumes:
  #     - ./frontend:/frontend
  #   ports:
  #     - 80:8080
