version: "3"
services:
  backend:
    build: ./backend
    command: yarn start
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
        # - "443:443"

  frontend:
    build: ./frontend
    command: yarn serve
    volumes:
      - ./frontend:/frontend
    ports:
      - 80:8080
certbot:
    build: ./certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-evsoul:/webroots/evsoul.com/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

volumes:
  certbot-webroot-evsoul:
  certbot-letsencrypt:
